AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/initializers/**/*'
    - 'config/environments/**/*'
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120
StringLiterals:
  Enabled: false
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolProc:
  IgnoredMethods:
    - respond_to
    - define_method
    - throttle
